default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid_19_province_lookup_development
  username: stefano
  password: stefano
  host: localhost

test:
  <<: *default
  database: covid_19_province_lookup_development
  username: stefano
  password: stefano
  host: localhost

production:
  <<: *default
  database: dehjrmqjo4i929
  username: msblqrgzomagub
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: ec2-54-228-251-117.eu-west-1.compute.amazonaws.com
