default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid_19_province_lookup_development
  username: stefano
  password: stefano
  host: localhost

test:
  <<: *default
  database: covid_19_province_lookup_development
  username: stefano
  password: stefano
  host: localhost

production:
  <<: *default
  database: daj1sov8u0uvkr
  username: kkvaouceqssaxf
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: ec2-176-34-97-213.eu-west-1.compute.amazonaws.com
